<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\Common\Common.csproj" />
    <ProjectReference Include="..\BuildingBlocks\Authentication\Authentication.csproj" />
    <ProjectReference Include="..\BuildingBlocks\EventBus\EventBus.csproj" />
    <ProjectReference Include="..\Catalog.Domain\Catalog.Domain.csproj" />
    <ProjectReference Include="..\BuildingBlocks\ApiClients\ApiClients.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Common\" />
    <None Remove="Common\Interfaces\" />
    <None Remove="Features\" />
    <None Remove="Features\Stores\Commands\UpdateStore\" />
    <None Remove="Features\Stores\Commands\DeleteStore\" />
    <None Remove="Features\Stores\Queries\" />
    <None Remove="Features\Stores\Queries\GetStore\" />
    <None Remove="Features\Stores\Queries\GetStoresWithPagination\" />
    <None Remove="Features\Uploads\" />
    <None Remove="Features\Uploads\Commands\" />
    <None Remove="Features\Uploads\Commands\CreateUpload\" />
    <None Remove="Features\Uploads\Models\" />
    <None Remove="Features\Stores\Queries\GetStores\" />
    <None Remove="Features\Banners\" />
    <None Remove="Features\Banners\Commands\" />
    <None Remove="Features\Banners\Models\" />
    <None Remove="Features\Banners\Queries\" />
    <None Remove="Features\Banners\Commands\CreateBanner\" />
    <None Remove="Features\Banners\Commands\UpdateBanner\" />
    <None Remove="Features\Banners\Commands\DeleteBanner\" />
    <None Remove="Features\Banners\Queries\GetBanner\" />
    <None Remove="Features\Banners\Queries\GetBannersWithPagination\" />
    <None Remove="Features\UserStores\" />
    <None Remove="Features\UserStores\Commands\" />
    <None Remove="Features\UserStores\Models\" />
    <None Remove="Features\UserStores\Queries\" />
    <None Remove="Features\UserStores\Commands\SentUserToStore\" />
    <None Remove="Features\UserStores\Queries\GetUserStore\" />
    <None Remove="Features\Stores\Queries\GetStoreForMerchantsWithPagination\" />
    <None Remove="Features\Produts\Queries\GetProducts\" />
    <None Remove="Features\Calendars\" />
    <None Remove="Features\CalendarTypes\" />
    <None Remove="Features\CalendarTypes\Commands\" />
    <None Remove="Features\CalendarTypes\Models\" />
    <None Remove="Features\CalendarTypes\Queries\" />
    <None Remove="Features\Calendars\Commands\" />
    <None Remove="Features\Calendars\Models\" />
    <None Remove="Features\Calendars\Queries\" />
    <None Remove="Features\CalendarTypes\Commands\CreateCalendarType\" />
    <None Remove="Features\CalendarTypes\Commands\UpdateCalendarType\" />
    <None Remove="Features\CalendarTypes\Commands\DeleteCalendarType\" />
    <None Remove="Features\Calendars\Commands\CreateCalendar\" />
    <None Remove="Features\CalendarTypes\Queries\GetCalendarType\" />
    <None Remove="Features\CalendarTypes\Queries\GetCalendarTypes\" />
    <None Remove="Features\CalendarTypes\Queries\GetCalendarTypesWithPagination\" />
    <None Remove="Features\Calendars\Commands\UpdateCaledar\" />
    <None Remove="Features\Calendars\Commands\DeleteCalendar\" />
    <None Remove="Features\Calendars\Queries\GetCalendar\" />
    <None Remove="Features\Calendars\Queries\GetCalendars\" />
    <None Remove="Features\Calendars\Queries\GetCalendarsWithPagination\" />
    <None Remove="Features\Merchants\" />
    <None Remove="Features\ServicePackages\" />
    <None Remove="Features\Merchants\Commads\" />
    <None Remove="Features\Merchants\Models\" />
    <None Remove="Features\Merchants\Queries\" />
    <None Remove="Features\Merchants\Commads\CreateMerchant\" />
    <None Remove="Features\Merchants\Commads\UpdateMerchant\" />
    <None Remove="Features\Merchants\Commads\DeleteMerchant\" />
    <None Remove="Features\Merchants\Queries\GetMerchant\" />
    <None Remove="Features\Merchants\Queries\GetMerchants\" />
    <None Remove="Features\Merchants\Queries\GetMerchantsWithPagination\" />
    <None Remove="Features\Rewards\" />
    <None Remove="Features\Rewards\Commands\" />
    <None Remove="Features\Rewards\Models\" />
    <None Remove="Features\Rewards\Queries\" />
    <None Remove="Features\Rewards\Commands\UpdateReward\" />
    <None Remove="Features\Rewards\Commands\DeleteReward\" />
    <None Remove="Features\Rewards\Commands\CreateReward\" />
    <None Remove="Features\Rewards\Queries\GetReward\" />
    <None Remove="Features\Rewards\Queries\GetRewards\" />
    <None Remove="Features\Rewards\Queries\GetRewardsWithPagination\" />
    <None Remove="Features\ReviewStores\" />
    <None Remove="Features\ReviewStores\Commands\" />
    <None Remove="Features\ReviewStores\Models\" />
    <None Remove="Features\ReviewStores\Queries\" />
    <None Remove="Features\ReviewStores\Commands\CreateReviewStore\" />
    <None Remove="Features\ReviewStores\Commands\UpdateReviewStore\" />
    <None Remove="Features\ReviewStores\Commands\DeleteReviewStore\" />
    <None Remove="Features\ReviewStores\Queries\GetReviewStore\" />
    <None Remove="Features\ReviewStores\Queries\GetReviewStores\" />
    <None Remove="Features\ReviewStores\Queries\GetReviewStoresWithPagination\" />
    <None Remove="Features\Categories\" />
    <None Remove="Features\Categories\Commands\" />
    <None Remove="Features\Categories\Commands\CreateCategory\" />
    <None Remove="Features\Categories\Models\" />
    <None Remove="Features\Categories\Commands\UpdateCategory\" />
    <None Remove="Features\Categories\Commands\DeleteCategory\" />
    <None Remove="Features\Categories\Queries\" />
    <None Remove="Features\Categories\Queries\GetCategory\" />
    <None Remove="Features\Categories\Queries\GetCategories\" />
    <None Remove="Features\Categories\Queries\GetCategoryWithPagination\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Common\Interfaces\" />
    <Folder Include="Features\AppDeepLinks\Commands\DeleteAppDeepLink\" />
    <Folder Include="Features\AppDeepLinks\Commands\UpdateAppDeepLink\" />
    <Folder Include="Features\Stores\Commands\UpdateStore\" />
    <Folder Include="Features\Stores\Commands\DeleteStore\" />
    <Folder Include="Features\Stores\Queries\GetStoresWithPagination\" />
    <Folder Include="Features\Uploads\" />
    <Folder Include="Features\Uploads\Commands\" />
    <Folder Include="Features\Uploads\Commands\CreateUpload\" />
    <Folder Include="Features\Uploads\Models\" />
    <Folder Include="Features\Stores\Queries\GetStores\" />
    <Folder Include="Features\Banners\" />
    <Folder Include="Features\Banners\Commands\" />
    <Folder Include="Features\Banners\Models\" />
    <Folder Include="Features\Banners\Queries\" />
    <Folder Include="Features\Banners\Commands\CreateBanner\" />
    <Folder Include="Features\Banners\Commands\UpdateBanner\" />
    <Folder Include="Features\Banners\Commands\DeleteBanner\" />
    <Folder Include="Features\Banners\Queries\GetBanner\" />
    <Folder Include="Features\Banners\Queries\GetBannersWithPagination\" />
    <Folder Include="Features\UserStores\" />
    <Folder Include="Features\UserStores\Commands\" />
    <Folder Include="Features\UserStores\Models\" />
    <Folder Include="Features\UserStores\Queries\" />
    <Folder Include="Features\UserStores\Commands\SentUserToStore\" />
    <Folder Include="Features\UserStores\Queries\GetUserStore\" />
    <Folder Include="Features\Stores\Queries\GetStoreForMerchantsWithPagination\" />
    <Folder Include="Features\Stores\Queries\GetStores\" />
    <Folder Include="Features\Produts\Queries\GetProducts\" />
    <Folder Include="Features\CalendarTypes\" />
    <Folder Include="Features\CalendarTypes\Commands\" />
    <Folder Include="Features\CalendarTypes\Models\" />
    <Folder Include="Features\CalendarTypes\Queries\" />
    <Folder Include="Features\Calendars\Commands\" />
    <Folder Include="Features\Calendars\Models\" />
    <Folder Include="Features\CalendarTypes\Commands\CreateCalendarType\" />
    <Folder Include="Features\CalendarTypes\Commands\UpdateCalendarType\" />
    <Folder Include="Features\CalendarTypes\Commands\DeleteCalendarType\" />
    <Folder Include="Features\Calendars\Commands\CreateCalendar\" />
    <Folder Include="Features\CalendarTypes\Queries\GetCalendarType\" />
    <Folder Include="Features\CalendarTypes\Queries\GetCalendarTypes\" />
    <Folder Include="Features\CalendarTypes\Queries\GetCalendarTypesWithPagination\" />
    <Folder Include="Features\Calendars\Commands\UpdateCaledar\" />
    <Folder Include="Features\Calendars\Commands\DeleteCalendar\" />
    <Folder Include="Features\Calendars\Queries\GetCalendar\" />
    <Folder Include="Features\Calendars\Queries\GetCalendars\" />
    <Folder Include="Features\Calendars\Queries\GetCalendarsWithPagination\" />
    <Folder Include="Features\Merchants\" />
    <Folder Include="Features\Merchants\Commads\" />
    <Folder Include="Features\Merchants\Models\" />
    <Folder Include="Features\Merchants\Queries\" />
    <Folder Include="Features\Merchants\Commads\CreateMerchant\" />
    <Folder Include="Features\Merchants\Commads\UpdateMerchant\" />
    <Folder Include="Features\Merchants\Commads\DeleteMerchant\" />
    <Folder Include="Features\Merchants\Queries\GetMerchant\" />
    <Folder Include="Features\Merchants\Queries\GetMerchants\" />
    <Folder Include="Features\Merchants\Queries\GetMerchantsWithPagination\" />
    <Folder Include="Features\Rewards\" />
    <Folder Include="Features\Rewards\Commands\" />
    <Folder Include="Features\Rewards\Models\" />
    <Folder Include="Features\Rewards\Queries\" />
    <Folder Include="Features\Rewards\Commands\UpdateReward\" />
    <Folder Include="Features\Rewards\Commands\DeleteReward\" />
    <Folder Include="Features\Rewards\Commands\CreateReward\" />
    <Folder Include="Features\Rewards\Queries\GetReward\" />
    <Folder Include="Features\Rewards\Queries\GetRewards\" />
    <Folder Include="Features\Rewards\Queries\GetRewardsWithPagination\" />
    <Folder Include="Features\ReviewStores\Commands\" />
    <Folder Include="Features\ReviewStores\Commands\CreateReviewStore\" />
    <Folder Include="Features\ReviewStores\Commands\UpdateReviewStore\" />
    <Folder Include="Features\ReviewStores\Commands\DeleteReviewStore\" />
    <Folder Include="Features\ReviewStores\Queries\GetReviewStore\" />
    <Folder Include="Features\ReviewStores\Queries\GetReviewStoresWithPagination\" />
    <Folder Include="Features\Categories\" />
    <Folder Include="Features\Categories\Commands\" />
    <Folder Include="Features\Categories\Commands\CreateCategory\" />
    <Folder Include="Features\Categories\Models\" />
    <Folder Include="Features\Categories\Commands\UpdateCategory\" />
    <Folder Include="Features\Categories\Commands\DeleteCategory\" />
    <Folder Include="Features\Categories\Queries\" />
    <Folder Include="Features\Categories\Queries\GetCategory\" />
    <Folder Include="Features\Categories\Queries\GetCategories\" />
    <Folder Include="Features\Categories\Queries\GetCategoryWithPagination\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>
</Project>
