<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\Common\Common.csproj" />
    <ProjectReference Include="..\BuildingBlocks\Authentication\Authentication.csproj" />
    <ProjectReference Include="..\BuildingBlocks\EventBus\EventBus.csproj" />
    <ProjectReference Include="..\Catalog.Domain\Catalog.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Common\" />
    <None Remove="Common\Interfaces\" />
    <None Remove="Features\" />
    <None Remove="Features\Stores\Commands\UpdateStore\" />
    <None Remove="Features\Stores\Commands\DeleteStore\" />
    <None Remove="Features\Stores\Queries\" />
    <None Remove="Features\Stores\Queries\GetStore\" />
    <None Remove="Features\Stores\Queries\GetStoresWithPagination\" />
    <None Remove="Features\Uploads\" />
    <None Remove="Features\Uploads\Commands\" />
    <None Remove="Features\Uploads\Commands\CreateUpload\" />
    <None Remove="Features\Uploads\Models\" />
    <None Remove="Features\Stores\Queries\GetStores\" />
    <None Remove="Features\Banners\" />
    <None Remove="Features\Banners\Commands\" />
    <None Remove="Features\Banners\Models\" />
    <None Remove="Features\Banners\Queries\" />
    <None Remove="Features\Banners\Commands\CreateBanner\" />
    <None Remove="Features\Banners\Commands\UpdateBanner\" />
    <None Remove="Features\Banners\Commands\DeleteBanner\" />
    <None Remove="Features\Banners\Queries\GetBanner\" />
    <None Remove="Features\Banners\Queries\GetBannersWithPagination\" />
    <None Remove="Features\UserStores\" />
    <None Remove="Features\UserStores\Commands\" />
    <None Remove="Features\UserStores\Models\" />
    <None Remove="Features\UserStores\Queries\" />
    <None Remove="Features\UserStores\Commands\SentUserToStore\" />
    <None Remove="Features\UserStores\Queries\GetUserStore\" />
    <None Remove="Features\Stores\Queries\GetStoreForMerchantsWithPagination\" />
    <None Remove="Features\Produts\Queries\GetProducts\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Common\Interfaces\" />
    <Folder Include="Features\" />
    <Folder Include="Features\Stores\Commands\UpdateStore\" />
    <Folder Include="Features\Stores\Commands\DeleteStore\" />
    <Folder Include="Features\Stores\Queries\" />
    <Folder Include="Features\Stores\Queries\GetStore\" />
    <Folder Include="Features\Stores\Queries\GetStoresWithPagination\" />
    <Folder Include="Features\Uploads\" />
    <Folder Include="Features\Uploads\Commands\" />
    <Folder Include="Features\Uploads\Commands\CreateUpload\" />
    <Folder Include="Features\Uploads\Models\" />
    <Folder Include="Features\Stores\Queries\GetStores\" />
    <Folder Include="Features\Banners\" />
    <Folder Include="Features\Banners\Commands\" />
    <Folder Include="Features\Banners\Models\" />
    <Folder Include="Features\Banners\Queries\" />
    <Folder Include="Features\Banners\Commands\CreateBanner\" />
    <Folder Include="Features\Banners\Commands\UpdateBanner\" />
    <Folder Include="Features\Banners\Commands\DeleteBanner\" />
    <Folder Include="Features\Banners\Queries\GetBanner\" />
    <Folder Include="Features\Banners\Queries\GetBannersWithPagination\" />
    <Folder Include="Features\UserStores\" />
    <Folder Include="Features\UserStores\Commands\" />
    <Folder Include="Features\UserStores\Models\" />
    <Folder Include="Features\UserStores\Queries\" />
    <Folder Include="Features\UserStores\Commands\SentUserToStore\" />
    <Folder Include="Features\UserStores\Queries\GetUserStore\" />
    <Folder Include="Features\Stores\Queries\GetStoreForMerchantsWithPagination\" />
    <Folder Include="Features\Stores\Queries\GetStores\" />
    <Folder Include="Features\Produts\Queries\GetProducts\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>
</Project>
